# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\main\python\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1173, 756)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.selectProjectGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.selectProjectGroupBox.setMinimumSize(QtCore.QSize(331, 691))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectProjectGroupBox.setFont(font)
        self.selectProjectGroupBox.setObjectName("selectProjectGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.selectProjectGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.selectProjectCheckButton = QtWidgets.QPushButton(self.selectProjectGroupBox)
        self.selectProjectCheckButton.setMinimumSize(QtCore.QSize(100, 25))
        self.selectProjectCheckButton.setObjectName("selectProjectCheckButton")
        self.gridLayout_3.addWidget(self.selectProjectCheckButton, 1, 0, 1, 1)
        self.selectProjectUncheckButton = QtWidgets.QPushButton(self.selectProjectGroupBox)
        self.selectProjectUncheckButton.setMinimumSize(QtCore.QSize(100, 25))
        self.selectProjectUncheckButton.setObjectName("selectProjectUncheckButton")
        self.gridLayout_3.addWidget(self.selectProjectUncheckButton, 1, 1, 1, 1)
        self.selectProjectListWidget = QtWidgets.QListWidget(self.selectProjectGroupBox)
        self.selectProjectListWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.selectProjectListWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.selectProjectListWidget.setFont(font)
        self.selectProjectListWidget.setIconSize(QtCore.QSize(24, 24))
        self.selectProjectListWidget.setObjectName("selectProjectListWidget")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/base/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectProjectListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/base/txt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectProjectListWidget.addItem(item)
        self.gridLayout_3.addWidget(self.selectProjectListWidget, 0, 0, 1, 2)
        self.gridLayout_6.addWidget(self.selectProjectGroupBox, 0, 0, 3, 1)
        self.openProjectGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.openProjectGroupBox.setMinimumSize(QtCore.QSize(791, 71))
        self.openProjectGroupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.openProjectGroupBox.setFont(font)
        self.openProjectGroupBox.setObjectName("openProjectGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.openProjectGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.openProjectLineEdit = QtWidgets.QLineEdit(self.openProjectGroupBox)
        self.openProjectLineEdit.setMinimumSize(QtCore.QSize(441, 40))
        self.openProjectLineEdit.setObjectName("openProjectLineEdit")
        self.gridLayout.addWidget(self.openProjectLineEdit, 0, 0, 1, 1)
        self.openProjectButton = QtWidgets.QPushButton(self.openProjectGroupBox)
        self.openProjectButton.setMinimumSize(QtCore.QSize(91, 41))
        self.openProjectButton.setObjectName("openProjectButton")
        self.gridLayout.addWidget(self.openProjectButton, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.openProjectGroupBox, 0, 1, 1, 2)
        self.selectTableGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.selectTableGroupBox.setMinimumSize(QtCore.QSize(371, 581))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectTableGroupBox.setFont(font)
        self.selectTableGroupBox.setObjectName("selectTableGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.selectTableGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.selectTableListWidget = QtWidgets.QListWidget(self.selectTableGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.selectTableListWidget.setFont(font)
        self.selectTableListWidget.setObjectName("selectTableListWidget")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectTableListWidget.addItem(item)
        self.gridLayout_2.addWidget(self.selectTableListWidget, 0, 0, 1, 2)
        self.selectTableUncheckButton = QtWidgets.QPushButton(self.selectTableGroupBox)
        self.selectTableUncheckButton.setObjectName("selectTableUncheckButton")
        self.gridLayout_2.addWidget(self.selectTableUncheckButton, 1, 1, 1, 1)
        self.selectTableCheckButton = QtWidgets.QPushButton(self.selectTableGroupBox)
        self.selectTableCheckButton.setObjectName("selectTableCheckButton")
        self.gridLayout_2.addWidget(self.selectTableCheckButton, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.selectTableGroupBox, 1, 1, 2, 1)
        self.extractGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.extractGroupBox.setMinimumSize(QtCore.QSize(411, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.extractGroupBox.setFont(font)
        self.extractGroupBox.setObjectName("extractGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.extractGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.extractComboBox = QtWidgets.QComboBox(self.extractGroupBox)
        self.extractComboBox.setObjectName("extractComboBox")
        self.extractComboBox.addItem("")
        self.extractComboBox.addItem("")
        self.extractComboBox.addItem("")
        self.extractComboBox.addItem("")
        self.gridLayout_4.addWidget(self.extractComboBox, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.extractGroupBox, 1, 2, 1, 1)
        self.outputGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.outputGroupBox.setMinimumSize(QtCore.QSize(411, 451))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.outputGroupBox.setFont(font)
        self.outputGroupBox.setObjectName("outputGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.outputGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.outputBrowseButton = QtWidgets.QPushButton(self.outputGroupBox)
        self.outputBrowseButton.setMinimumSize(QtCore.QSize(91, 30))
        self.outputBrowseButton.setObjectName("outputBrowseButton")
        self.gridLayout_5.addWidget(self.outputBrowseButton, 0, 1, 1, 1)
        self.outputLineEdit = QtWidgets.QLineEdit(self.outputGroupBox)
        self.outputLineEdit.setMinimumSize(QtCore.QSize(281, 30))
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.gridLayout_5.addWidget(self.outputLineEdit, 0, 0, 1, 1)
        self.outputListWidget = QtWidgets.QListWidget(self.outputGroupBox)
        self.outputListWidget.setMinimumSize(QtCore.QSize(391, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.outputListWidget.setFont(font)
        self.outputListWidget.setIconSize(QtCore.QSize(24, 24))
        self.outputListWidget.setObjectName("outputListWidget")
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/base/excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.outputListWidget.addItem(item)
        self.gridLayout_5.addWidget(self.outputListWidget, 1, 0, 1, 2)
        self.extractButton = QtWidgets.QPushButton(self.outputGroupBox)
        self.extractButton.setObjectName("extractButton")
        self.gridLayout_5.addWidget(self.extractButton, 3, 0, 1, 2)
        self.gridLayout_6.addWidget(self.outputGroupBox, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1173, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menu_View = QtWidgets.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statusbar.setFont(font)
        self.statusbar.setAcceptDrops(False)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.actionAbout_Textract = QtWidgets.QAction(MainWindow)
        self.actionAbout_Textract.setObjectName("actionAbout_Textract")
        self.action_About_Textract = QtWidgets.QAction(MainWindow)
        self.action_About_Textract.setObjectName("action_About_Textract")
        self.action_About_Author = QtWidgets.QAction(MainWindow)
        self.action_About_Author.setObjectName("action_About_Author")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionQuit)
        self.menu_Help.addAction(self.action_About)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.action_About_Textract)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.action_About_Author)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Textract"))
        self.selectProjectGroupBox.setTitle(_translate("MainWindow", "Select Project Files"))
        self.selectProjectCheckButton.setText(_translate("MainWindow", "Check All"))
        self.selectProjectUncheckButton.setText(_translate("MainWindow", "Uncheck All"))
        __sortingEnabled = self.selectProjectListWidget.isSortingEnabled()
        self.selectProjectListWidget.setSortingEnabled(False)
        item = self.selectProjectListWidget.item(0)
        item.setText(_translate("MainWindow", "Sample Project File1"))
        item = self.selectProjectListWidget.item(1)
        item.setText(_translate("MainWindow", "Sample Project File2"))
        self.selectProjectListWidget.setSortingEnabled(__sortingEnabled)
        self.openProjectGroupBox.setTitle(_translate("MainWindow", "Open Project Directory"))
        self.openProjectButton.setText(_translate("MainWindow", "Browse"))
        self.selectTableGroupBox.setTitle(_translate("MainWindow", "Select Table Fields To Extract"))
        __sortingEnabled = self.selectTableListWidget.isSortingEnabled()
        self.selectTableListWidget.setSortingEnabled(False)
        item = self.selectTableListWidget.item(0)
        item.setText(_translate("MainWindow", "Sample Table Field 1"))
        self.selectTableListWidget.setSortingEnabled(__sortingEnabled)
        self.selectTableUncheckButton.setText(_translate("MainWindow", "Uncheck All"))
        self.selectTableCheckButton.setText(_translate("MainWindow", "Check All"))
        self.extractGroupBox.setTitle(_translate("MainWindow", "Extraction Criteria"))
        self.extractComboBox.setItemText(0, _translate("MainWindow", "All In One Table"))
        self.extractComboBox.setItemText(1, _translate("MainWindow", "Daily Table"))
        self.extractComboBox.setItemText(2, _translate("MainWindow", "Monthly Table"))
        self.extractComboBox.setItemText(3, _translate("MainWindow", "Yearly Table"))
        self.outputGroupBox.setTitle(_translate("MainWindow", "Output Directory"))
        self.outputBrowseButton.setText(_translate("MainWindow", "Browse"))
        __sortingEnabled = self.outputListWidget.isSortingEnabled()
        self.outputListWidget.setSortingEnabled(False)
        item = self.outputListWidget.item(0)
        item.setText(_translate("MainWindow", "Sample Output File 1"))
        self.outputListWidget.setSortingEnabled(__sortingEnabled)
        self.extractButton.setText(_translate("MainWindow", "Extract"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.menu_View.setTitle(_translate("MainWindow", "&View"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.action_About.setText(_translate("MainWindow", "&About"))
        self.actionAbout_Textract.setText(_translate("MainWindow", "About Textract"))
        self.action_About_Textract.setText(_translate("MainWindow", "&About Textract"))
        self.action_About_Author.setText(_translate("MainWindow", "&About Author"))


import ui.base_rc
